spring.application.name=crud_basic

# ==============================
# DESACTIVAR BASE DE DATOS (IMPORTANTE PARA RAILWAY)
# ==============================

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# ==============================
# PUERTO DINÁMICO PARA RAILWAY
# ==============================

# Usa el puerto que Railway asigna automáticamente
# Si no existe (en local), usa 8080
server.port=${PORT:8080}




















#spring.application.name=crud_basic
#url del servidor y base datos
#spring.datasource.url=jdbc:mysql://direcciónip:puerto/DBName
#spring.datasource.url=jdbc:mysql://localhost:3306/store
#user DB manager
#spring.datasource.username=root
#password user db manager
#spring.datasource.password=

#driver para conectar con la base de datos
#driver mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#configuraciones JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#puerto servidor
#server.port=8085